server:
  port: 8081

aws:
  s3:
    accessKey: AKIA2VGMYN6HWYBMO36P
    secretKey: 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
    region: us-east-1


spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher